name: Build & Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm install
        env:
          GYP_MSVS_VERSION: "2022"

      - name: Build & publish to GitHub Releases
        run: npm run release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GYP_MSVS_VERSION: "2022"
